#include <rex/runtime/guest.h>
#define STUB_KERNEL(x) __attribute__((alias("__imp__" #x))) PPC_FUNC(x); PPC_FUNC_IMPL(__imp__##x) { REXLOG_INFO("{} stub!", __FUNCTION__); return; }

// Stubs for imported functions not provided by rex
STUB_KERNEL(ExAllocatePoolWithTag)
STUB_KERNEL(IoCheckShareAccess)
STUB_KERNEL(IoCompleteRequest)
STUB_KERNEL(IoDeleteDevice)
STUB_KERNEL(IoDismountVolume)
STUB_KERNEL(IoInvalidDeviceRequest)
STUB_KERNEL(IoRemoveShareAccess)
STUB_KERNEL(IoSetShareAccess)
STUB_KERNEL(MicDeviceRequest)
STUB_KERNEL(ObIsTitleObject)
STUB_KERNEL(ObReferenceObject)
STUB_KERNEL(RmcDeviceRequest)
STUB_KERNEL(RtlUpcaseUnicodeChar)
STUB_KERNEL(XamBackgroundDownloadItemGetHistoryStatus)
STUB_KERNEL(XamBackgroundDownloadItemGetStatus)
STUB_KERNEL(XamBackgroundDownloadSetMode)
STUB_KERNEL(XamDeviceRemap)
STUB_KERNEL(XamInputControl)
STUB_KERNEL(XamInputRawState)
STUB_KERNEL(XAudioOverrideSpeakerConfig)
STUB_KERNEL(XamInputSendStayAliveRequest)
STUB_KERNEL(XamShowFriendsUI)
STUB_KERNEL(XamShowGamerCardUIForXUID)
STUB_KERNEL(XamShowMarketplaceDownloadItemsUI)
STUB_KERNEL(XamShowMarketplaceUI)
STUB_KERNEL(XamUserGetMembershipTierFromXUID)
STUB_KERNEL(XamUserGetOnlineCountryFromXUID)
STUB_KERNEL(XamVoiceSubmitPacket)

//xnet / internet sdtuff
STUB_KERNEL(XNetLogonGetTitleID)
STUB_KERNEL(NetDll_XNetCreateKey)
STUB_KERNEL(NetDll_XNetRegisterKey)
STUB_KERNEL(NetDll_XNetUnregisterKey)
STUB_KERNEL(NetDll_XNetServerToInAddr)
STUB_KERNEL(NetDll_XNetUnregisterInAddr)
STUB_KERNEL(NetDll_XNetConnect)
STUB_KERNEL(NetDll_XNetGetConnectStatus)
STUB_KERNEL(NetDll_XNetQosLookup)
STUB_KERNEL(NetDll_getsockname)
STUB_KERNEL(NetDll_getpeername)
STUB_KERNEL(NetDll_WSAGetOverlappedResult)
STUB_KERNEL(NetDll_XNetGetSystemLinkPort)

