[controller]
; Controller type to emulate
; TODO: get a list of these
type = 7

[rnd]
; Vertical sync mode: -1 = don't override, 0 = disable, 1 = enable
sync = -1

[venue]
; small_club_##:    01, 02, 03, 04, 05, 06, 10, 11, 13, 14, 15
; big_club_##:      01, 02, 04, 15, 17
; arena_##:         01, 04, 06, 07, 10, 11, 12
; festival_##:      01, 02
; video_##:         01, 02, 03, 04, 05, 06, 07
; black_background: none
; no_forced_venue:  false
; comma separated multi venues and classes of venues are also supported. EX:
; forced_venue = none, video, festival_02
; will randomly will pick between no venue, all 7 video venues, and festival_02
forced_venue = false

[window]
; Start in fullscreen mode: true or false
fullscreen = false
; window size (does not currently control resolution)
width = 1280
height = 720

[game]
; skip the splash screens when the game has finished initing
fast_start = false
;disable background menu music: true or false
disable_metamusic = false

[debug]
; Show the debug overlay (FPS counter): true or false
overlay = true
; Log level: trace, debug, info, warn, error, critical
log_level = info

