[controller]
; Controller type to emulate
; TODO: get a list of these
type = 7

[rnd]
; Vertical sync mode: -1 = don't override, 0 = disable, 1 = enable
sync = 1

[venue]
; small_club_##:    01, 02, 03, 04, 05, 06, 10, 11, 13, 14, 15
; big_club_##:      01, 02, 04, 15, 17
; arena_##:         01, 04, 06, 07, 10, 11, 12
; festival_##:      01, 02
; video_##:         01, 02, 03, 04, 05, 06, 07
; black_background: none
; no_forced_venue:  false
; comma separated multi venues and classes of venues are also supported. EX:
; forced_venue = none, video, festival_02
; will randomly will pick between no venue, all 7 video venues, and festival_02
forced_venue = false

[window]
; Start in fullscreen mode: true or false
fullscreen = false
; window size (does not currently control resolution)
width = 1280
height = 720

[game]
; skip the splash screens when the game has finished initing
fast_start = false
;disable background menu music: true or false
disable_metamusic = false
; Force the game to run in a specific language
; You can also do this by passing "-lang X" as a launch argument
; eng = English
; esl = Spanish
; fre = French
; ita = Italian
; deu = German
lang = eng

[graphics]
; Disable approximate lighting
; works around a graphical bug in current versions of rexglue
; will be removed in the future when this is not necessary anymore
disable_approximate_lights = true
; disables the use of the hair shader variation on materials
disable_hair_shader = false
; force all materials to not use an environ, basically becoming fullbright for most things
fullbright = false
; enables or disables compression of textures of characters
; if enabled, readback resolve will be required otherwise the textures will appear bugged!
compress_character_textures = false

[memory]
; Override heap sizes (0 = use default from mem.dta)
; Default main heap: 105000000, default char heap: 32000000
; these cannot add up to exceed 0x40000000 or the game will crash on start
main_heap_size = 0
char_heap_size = 0

[debug]
; Show the debug overlay (FPS counter): true or false
overlay = true
; Log level: trace, debug, info, warn, error, critical
log_level = info

